apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: coffeeshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: www.meraviglioso.id.vn
    http:
      paths:
      - path: /proxy(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: proxy
            port:
              number: 5000
