apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/data/rabbitmq
  persistentVolumeReclaimPolicy: Retain
