apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meraviglioso-id-vn-cert
  namespace: coffeeshop
spec:
  secretName: meraviglioso-id-vn-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: huyen.meraviglioso.id.vn
  dnsNames:
    - huyen.meraviglioso.id.vn
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
