apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: coffeeshop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ttmhuyen2110@gmail.com
    solvers:
    - http01:
        ingress:
          class: nginx