apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.15/manifests/install.yaml
  # - argocd-vault-plugin.yaml
patches:
- path: agocd-cm-plugin.yml
- path: argo-cd-repo-server-ksops-patch.yml

