server:
  service:
    type: LoadBalancer
    servicePortHttp: 30900
    servicePortHttps: 30901

configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
    
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: gpg-secret
      secret:
        secretName: gpg-private-key  # your secret with private.key

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/kustomize
      subPath: kustomize
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
    - name: gpg-secret
      mountPath: /home/argocd/.gnupg
      readOnly: true

  env:
    - name: GNUPGHOME
      value: /home/argocd/.gnupg
