apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: meraviglioso8/go-coffeeshop-product:dev-latest
        ports:
          - containerPort: 5001
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: coffeeshop-config
                key: APP_NAME
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 40m
            memory: 64Mi