apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista
  namespace: coffeeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
      - name: barista
        image: meraviglioso8/go-coffeeshop-barista:dev-latest
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: coffeeshop-config
                key: APP_NAME
          - name: IN_DOCKER
            value: "true"
          - name: PG_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_URL
          - name: PG_DSN_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_DSN_URL
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_URL
        resources:
          requests:
            cpu: 10m
            memory: 8Mi
          limits:
            cpu: 40m
            memory: 64Mi
